### ISSUE TITLE
Login failed with account password

### ISSUE THREAD

**Issue by fishmisswater** [realsirjoe/instagram-scraper#3]
I'm in China(My IP is in US), It's failed when I used "Instagram.with_credentials" to login:
Traceback (most recent call last):
  File "C:\python3\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\python3\lib\site-packages\urllib3\util\connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\python3\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

I try to add proxy to see detail:
poxy = {'https': 'https://127.0.0.1:8080'}
instagram.set_proxies(poxy)
but my tool(burp suite) didn't get any http requests。if want to get the https request, need to change souce code Manually that add "verify=False" in requests

**Comment by realsirjoe** [comment]
If you installed the scraper with pip try if you can execute this script (it doesnt require any login credientials, so we can eliminate the probablility of it being caused by your used account, and we don't leak info to open proxies) for the proxies I used just some free https proxies (you may need to edit them since they might not be valid any more, just try a few proxies you find online) 
```
from igramscraper.instagram import Instagram

proxies = {
    'http': 'http://192.203.80.148:8080',
    'https': 'http://192.203.80.148:8080',
}

instagram = Instagram()

instagram.set_proxies(proxies)
account = instagram.get_account_by_id('3')
print(account)
```

When executing this script I get the following output:

```
Account info:
Id: 3
Username: kevin
Full Name: Kevin Systrom
Bio: Co-founder, former CEO of @instagram
Profile Pic Url: <bound method Account.get_profile_picture_url of <igramscraper.model.account.Account object at 0x1037542e8>>
External url: https://mastersofscale.com/kevin-systrom-how-to-keep-it-simple-while-scaling-big/
Number of published posts: -
Number of followers: 8053047
Number of follows: 601
Is private: False
Is verified: True
```

**Comment by realsirjoe** [comment]
If that did work for you keep in mind that if you create an instagram object with credentials you still need to login seperatly:

```
instagram = Instagram.with_credentials('username', 'password', 'cachefolderpath')
instagram.login() 
```

**Comment by fishmisswater** [comment]
I do use pip to install it. But still not working. Maybe it's caused by the Chinese Internet. :joy:
`from igramscraper.instagram import Instagram
instagram = Instagram()
account = instagram.get_account_by_id(3)
print(account)`

TimeoutError: [WinError 10060] The connection attempt failed because the connecting party did not respond correctly or the connected host did not respond after a period of time.

**Comment by realsirjoe** [comment]
Try ping www.python.org and telnet www.python.org port_nr

**Comment by fishmisswater** [comment]
Testing at home yesterday was normal, and it was almost certain that the link layer packet was baned on the company side (only the application layer, such as http, could access the public network).

**Comment by realsirjoe** [comment]
Great! Sure you’re welcome

**Comment by ivurs** [comment]
ProxyError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /miaangler (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x116f3abe0>: Failed to establish a new connection: [Errno 60] Operation timed out',)))
