### ISSUE TITLE
Retrieve media location

### ISSUE THREAD

**Issue by mattiacampana** [realsirjoe/instagram-scraper#57]
How can I get the location tag associated with a specific media?

**Comment by jkurtz678** [comment]
Some parts of this project seem to be broken, most likely due to changes with instagram. Every time I have tried using 'media.location_id' it returns 'none', even on media I know has location ids. However, as long as I login first, get_medias_by_location_id() has been working for me.

Its also worth noting that not all instagram posts have location tags. I found this article to be helpful to understanding how location tags work in instagram: https://havecamerawilltravel.com/photographer/instagram-location-search

**Comment by mattiacampana** [comment]
get_medias_by_location_id() retrieves the media tagged with a specific location_id. On the other hand, I would like to get the location specified in a specific post (ofc, if specified by the user).

**Comment by haixuanTao** [comment]
Being connected you can retrieve the location of a media at the attribute ``` media.location_id, media.location_name, media.location_slug ``` took me a while to find. Hope it can help other in the future

**Comment by realsirjoe** [comment]
solved
